"""
Preprocess Barcelona Points of Interest (POI) into a labeled parquet.

Input:  data/raw/poi/opendatabcn_pics-csv.csv  — 878 POIs with coordinates
Output: data/processed/poi/poi.parquet

Each POI is assigned one of 15 categories relevant to Bicing demand analysis.
Labeling was done by an LLM (Claude) based on POI names and context.
"""

import logging
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parents[2]
RAW_FILE = ROOT / "data" / "raw" / "poi" / "opendatabcn_pics-csv.csv"
OUT_DIR = ROOT / "data" / "processed" / "poi"
OUT_FILE = OUT_DIR / "poi.parquet"

KEEP_COLS = [
    "register_id",
    "name",
    "addresses_road_name",
    "addresses_start_street_number",
    "addresses_neighborhood_name",
    "addresses_district_name",
    "addresses_zip_code",
    "addresses_main_address",
    "geo_epgs_4326_lat",
    "geo_epgs_4326_lon",
    "timetable",
]

# ---------------------------------------------------------------------------
# LLM-assigned category labels (Claude, May 2026)
# Categories: Museum / Gallery | Heritage / Architecture | Park / Garden |
#   Beach / Waterfront | University / Education | Library / Civic Center |
#   Market | Shopping Center | Sports Facility | Cultural Venue |
#   Transport Hub | Healthcare | Religious Site | Hotel / Hospitality | Other
# ---------------------------------------------------------------------------
LABELS: dict[str, str] = {
    '"Vivendes" del Congrés Eucarístic': "Heritage / Architecture",
    "'La Masia' del Barça": "Heritage / Architecture",
    "Acàdemia Blancafort - Antiga Editorial Seguí": "Heritage / Architecture",
    "Alberg In-Out - AJ000427": "Hotel / Hospitality",
    "Antic Dispensari Antituberculós": "Heritage / Architecture",
    "Antic Monòlit Dedicat a la Legión Condor": "Heritage / Architecture",
    "Antiga Biblioteca Infantil del GATCPAC": "Heritage / Architecture",
    "Antiga Biblioteca Pública de Sant Andreu de Palomar": "Heritage / Architecture",
    "Antiga Estació de Rodalies Sant Andreu Comtal de RENFE": "Heritage / Architecture",
    "Antiga Foneria de Canons": "Heritage / Architecture",
    "Antiga Fàbrica Can Batlló": "Heritage / Architecture",
    "Antiga Fàbrica Estrella Damm": "Heritage / Architecture",
    "Antiga Fàbrica d'Estampació Tèxtil Can Ricart": "Heritage / Architecture",
    "Antiga Subcentral Elèctrica de la Barceloneta": "Heritage / Architecture",
    "Associació Catalana per la Integració i el Desenvolupament Humà": "Other",
    "Associació Cultural El Raval El Lokal": "Other",
    "Associació Eix Comercial de Sant Andreu": "Shopping Center",
    "Associació Nou Barris Centre Comerç": "Shopping Center",
    "Associació Rambla de Catalunya": "Other",
    "Associació Sant Martí Eix Comercial": "Shopping Center",
    "Associació Sants Establiments Units": "Shopping Center",
    "Associació Sarrià Eix Comercial": "Shopping Center",
    "Associació Xarxa de Consum Solidari": "Other",
    "Associació d'Amics del Passeig de Gràcia": "Other",
    "Associació d'Emprenedors del Clot - Eix Clot": "Shopping Center",
    "Associació de Botiguers i Professionals Eix Maragall": "Shopping Center",
    "Associació de Comerciants del Carrer Gran de Gràcia": "Shopping Center",
    "Associació de Comerciants i Professionals Barnavasi": "Shopping Center",
    "Associació de Comerciants i Veïns de Creu Coberta": "Shopping Center",
    "Ateneu  Sant Andreu": "Library / Civic Center",
    "Ateneu Barcelonès": "Library / Civic Center",
    "Ateneu Popular de Sants": "Library / Civic Center",
    "Ateneu d'Innovació Digital i Democràtica - Canòdrom": "Library / Civic Center",
    "Ateneu de Fabricació Digital de Les Corts": "Library / Civic Center",
    "Avenç Obrer Català de Sant Andreu": "Other",
    "Avinguda Maria Cristina": "Other",
    "Avinguda de la Catedral": "Other",
    "BAU, Centre Universitari d'Arts i Disseny de Barcelona": "University / Education",
    "Bar Colòmbia": "Hotel / Hospitality",
    "Bar Marsella": "Hotel / Hospitality",
    "Bar Mestres": "Hotel / Hospitality",
    "Bar Musical London Bar": "Hotel / Hospitality",
    "Bar musical La Torre Rosa": "Hotel / Hospitality",
    "Barcelona - Casa Vídua Marfà": "Heritage / Architecture",
    "Base Nàutica Municipal de la Mar Bella": "Sports Facility",
    "Bibiblioteca Rector Gabriel Ferraté": "Library / Civic Center",
    "Biblioteca Barceloneta -  La Fraternitat": "Library / Civic Center",
    "Biblioteca Clarà": "Library / Civic Center",
    "Biblioteca Collserola - Josep Miracle": "Library / Civic Center",
    "Biblioteca Jaume Fuster": "Library / Civic Center",
    "Biblioteca Montserrat Abelló": "Library / Civic Center",
    "Biblioteca Vapor Vell": "Library / Civic Center",
    "Bodega Josefa": "Hotel / Hospitality",
    "Botiga Casa Rusca": "Heritage / Architecture",
    "Ca l'Aranyó": "Heritage / Architecture",
    "Ca l'Artés": "Heritage / Architecture",
    "Ca l'Estruc- Convent de les Germanes de l'Assumpció": "Religious Site",
    "Ca n'Andalet": "Heritage / Architecture",
    "Cafeteria Restaurant Cafè de l'Òpera": "Hotel / Hospitality",
    "CaixaForum Barcelona": "Museum / Gallery",
    "Camisseria Bonet": "Heritage / Architecture",
    "Camp Municipal de Futbol Narcís Sala": "Sports Facility",
    "Can Carreras": "Heritage / Architecture",
    "Can Culleretes": "Hotel / Hospitality",
    "Can Fabra": "Heritage / Architecture",
    "Can Fontanet - Centre d'Interpretació dels Tres Tombs de Sant Andreu": "Museum / Gallery",
    "Can Mazantini": "Heritage / Architecture",
    "Can Mora": "Heritage / Architecture",
    "Can Muntaner de Dalt": "Heritage / Architecture",
    "Can Pardal": "Heritage / Architecture",
    "Can Peguera": "Heritage / Architecture",
    "Can Trilla": "Heritage / Architecture",
    "Can Tusquets": "Heritage / Architecture",
    "Cansaladeria Puig": "Heritage / Architecture",
    "Capella dels Segadors": "Religious Site",
    "Carrer Aiguafreda": "Other",
    "Carrer Avió Plus Ultra": "Other",
    "Carrer Campo Florido": "Other",
    "Carrer Cienfuegos": "Other",
    "Carrer Coroleu": "Other",
    "Carrer Gran de Sant Andreu": "Other",
    "Carrer Grau": "Other",
    "Carrer Major de Sarrià": "Other",
    "Carrer Manigua": "Other",
    "Carrer Martí  i Franqués": "Other",
    "Carrer Matanzas": "Other",
    "Carrer Menéndez Pelayo": "Other",
    "Carrer Pinar del Rio": "Other",
    "Carrer Pons i Gallarza": "Other",
    "Carrer Puerto Príncipe": "Other",
    "Carrer Sant Gervasi de Cassoles": "Other",
    "Carrer de la Riereta": "Other",
    "Carrer de les Monges": "Other",
    "Casa - Fàbrica Erasme de Gònima": "Heritage / Architecture",
    "Casa -Fàbrica Vermell-Martí": "Heritage / Architecture",
    "Casa Agustí Trulla": "Heritage / Architecture",
    "Casa Almirall": "Hotel / Hospitality",
    "Casa Amatller": "Heritage / Architecture",
    "Casa Anoll": "Heritage / Architecture",
    "Casa Antoni Costa": "Heritage / Architecture",
    "Casa Barangé": "Heritage / Architecture",
    "Casa Bartomeu": "Heritage / Architecture",
    "Casa Batlló": "Heritage / Architecture",
    "Casa Bonaventura Ferrer": "Heritage / Architecture",
    "Casa Calvet": "Heritage / Architecture",
    "Casa Cama i Escurra": "Heritage / Architecture",
    "Casa Carreras": "Heritage / Architecture",
    "Casa Casas-Carbó": "Heritage / Architecture",
    "Casa Castellet": "Heritage / Architecture",
    "Casa Claudi Alsina": "Heritage / Architecture",
    "Casa Comalat": "Heritage / Architecture",
    "Casa Comas d' Argemir": "Heritage / Architecture",
    "Casa Company": "Heritage / Architecture",
    "Casa Concepció i Casa Comelles": "Heritage / Architecture",
    "Casa Cortina": "Heritage / Architecture",
    "Casa Doctor Genové": "Heritage / Architecture",
    "Casa Dolors Calm": "Heritage / Architecture",
    "Casa Domènech i Estapà": "Heritage / Architecture",
    "Casa Elisa Bremon d'Espina": "Heritage / Architecture",
    "Casa Eloy Detouche": "Heritage / Architecture",
    "Casa Enric Cera": "Heritage / Architecture",
    "Casa Estapé": "Heritage / Architecture",
    "Casa Eudald Obradors": "Heritage / Architecture",
    "Casa F. Homet": "Heritage / Architecture",
    "Casa Faiol - Casa de la Papallona": "Heritage / Architecture",
    "Casa Fargas": "Heritage / Architecture",
    "Casa Feliu Iglesies": "Heritage / Architecture",
    "Casa Fornells": "Heritage / Architecture",
    "Casa Francesc Cama": "Heritage / Architecture",
    "Casa Fàbrica Güell-Ramis": "Heritage / Architecture",
    "Casa Garriga Nogués": "Heritage / Architecture",
    "Casa Gaspar Galí": "Heritage / Architecture",
    "Casa Girona i Cuyàs": "Heritage / Architecture",
    "Casa Granell *Balmes": "Heritage / Architecture",
    "Casa Granell *Girona": "Heritage / Architecture",
    "Casa Gustà": "Heritage / Architecture",
    "Casa Hurtado": "Heritage / Architecture",
    "Casa Jaume Forn": "Heritage / Architecture",
    "Casa Joan Matas": "Heritage / Architecture",
    "Casa Josep Barnoles - La del Mico i el Gos": "Heritage / Architecture",
    "Casa Josep Castelló": "Heritage / Architecture",
    "Casa José de Ugarte": "Heritage / Architecture",
    "Casa Juncosa": "Heritage / Architecture",
    "Casa Lamadrid": "Heritage / Architecture",
    "Casa Lleó Morera": "Heritage / Architecture",
    "Casa Llopis Bofill": "Heritage / Architecture",
    "Casa Llorenç Camprubí": "Heritage / Architecture",
    "Casa Madurell": "Heritage / Architecture",
    "Casa Malagrida": "Heritage / Architecture",
    "Casa Manuel Colchero": "Heritage / Architecture",
    "Casa Marsans - Alberg Mare de Déu de Montserrat - AJ000084": "Hotel / Hospitality",
    "Casa Martí - Els Quatre Gats": "Hotel / Hospitality",
    "Casa Martí Trias i Domènech": "Heritage / Architecture",
    "Casa Miquel Cal Millàs": "Heritage / Architecture",
    "Casa Muley-Afid": "Heritage / Architecture",
    "Casa Muntadas": "Heritage / Architecture",
    "Casa Museu Gaudí": "Museum / Gallery",
    "Casa Parés": "Heritage / Architecture",
    "Casa Pere Jaqués": "Heritage / Architecture",
    "Casa Planells": "Heritage / Architecture",
    "Casa Pomar": "Heritage / Architecture",
    "Casa Queralt": "Heritage / Architecture",
    "Casa Queraltó": "Heritage / Architecture",
    "Casa Ramos": "Heritage / Architecture",
    "Casa Rosa Alemany": "Heritage / Architecture",
    "Casa Rubinat": "Heritage / Architecture",
    "Casa Sant Felip Neri": "Heritage / Architecture",
    "Casa Santurce": "Heritage / Architecture",
    "Casa Sarriera": "Heritage / Architecture",
    "Casa Serra": "Heritage / Architecture",
    "Casa Serès": "Heritage / Architecture",
    "Casa Terradas - Casa de les Punxes": "Heritage / Architecture",
    "Casa Thomas": "Heritage / Architecture",
    "Casa Tomàs Valls": "Heritage / Architecture",
    "Casa Vallet i Xiró": "Heritage / Architecture",
    "Casa Vicens": "Heritage / Architecture",
    "Casa Vidal": "Heritage / Architecture",
    "Casa Vilabella": "Heritage / Architecture",
    "Casa Vilaró": "Heritage / Architecture",
    "Casa Víctor Conill": "Heritage / Architecture",
    "Casa de l'Aigua. Museu d'Història de Barcelona": "Museum / Gallery",
    "Casa de la Lactància": "Heritage / Architecture",
    "Casa de la Marina": "Heritage / Architecture",
    "Casa de les Altures": "Heritage / Architecture",
    "Casa de l’Arquitectura de Barcelona - Antiga Seu Editorial Gustavo Gili": "Heritage / Architecture",
    "Casa del Guarda -  Espai d'Interpretació del Pantà de Vallvidrera": "Museum / Gallery",
    "Casa dels Ossos": "Heritage / Architecture",
    "Casal  Mas Guinardó": "Library / Civic Center",
    'Casal Catòlic de Sant Andreu - Àntic Casino "El Progrés"': "Heritage / Architecture",
    "Casal Cívic i Comunitari Barcelona - Can Guardiola": "Library / Civic Center",
    "Casal Cívic i Comunitari Barcelona - Magòria": "Library / Civic Center",
    "Casal Sant Jordi": "Library / Civic Center",
    "Casal de Barri Can Portabella": "Library / Civic Center",
    "Casal de Barri Font d'en Fargues": "Library / Civic Center",
    "Casal de Barri Pou de la Figuera": "Library / Civic Center",
    "Casernes d'Artilleria  de Sant Andreu": "Heritage / Architecture",
    "Cases Antoni Par": "Heritage / Architecture",
    "Cases Barates del Bon Pastor": "Heritage / Architecture",
    "Cases Blanques": "Heritage / Architecture",
    "Cases Folguera": "Heritage / Architecture",
    "Cases Francesc Farreras": "Heritage / Architecture",
    "Cases Josefa Villanueva": "Heritage / Architecture",
    "Cases Leandre Vidal": "Heritage / Architecture",
    "Cases Manuel Raventós": "Heritage / Architecture",
    "Cases Pascual i Pons": "Heritage / Architecture",
    "Cases Rocamora": "Heritage / Architecture",
    "Cases de menestrals": "Heritage / Architecture",
    "Cases modernistes del carrer de Sants": "Heritage / Architecture",
    "Castell de Montjuïc": "Heritage / Architecture",
    "Castell de Torre Baró": "Heritage / Architecture",
    "Castell dels Tres Dragons": "Heritage / Architecture",
    "Cementiri Les Corts": "Other",
    "Cementiri Montjuïc": "Other",
    "Cementiri Poblenou": "Other",
    "Cementiri Sant Andreu": "Other",
    "Cementiri Sant Genís": "Other",
    "Cementiri Sant Gervasi": "Other",
    "Cementiri Sarrià": "Other",
    "Cementiri d'Horta": "Other",
    "Centre Comercial Arenas de Barcelona": "Shopping Center",
    "Centre Comercial Diagonal Mar": "Shopping Center",
    "Centre Comercial El Centre de la Vila": "Shopping Center",
    "Centre Comercial L'Illa Diagonal": "Shopping Center",
    "Centre Comercial Maremàgnum": "Shopping Center",
    "Centre Comercial Westfield Glòries": "Shopping Center",
    "Centre Cultural La Farinera del Clot": "Cultural Venue",
    "Centre Cultural Teresa Pàmies": "Cultural Venue",
    "Centre Cívic  Vil·la Urània": "Library / Civic Center",
    "Centre Cívic Can Basté": "Library / Civic Center",
    "Centre Cívic Can Castelló": "Library / Civic Center",
    "Centre Cívic Can Deu": "Library / Civic Center",
    "Centre Cívic Can Felipa": "Library / Civic Center",
    "Centre Cívic Can Verdaguer": "Library / Civic Center",
    "Centre Cívic Casa Golferichs": "Library / Civic Center",
    "Centre Cívic Casa Orlandai": "Library / Civic Center",
    "Centre Cívic Casinet d'Hostafrancs": "Library / Civic Center",
    "Centre Cívic Cotxeres de Sants": "Library / Civic Center",
    "Centre Cívic El Coll - La Bruguera": "Library / Civic Center",
    "Centre Cívic Guinardó": "Library / Civic Center",
    "Centre Cívic La Sedeta": "Library / Civic Center",
    "Centre Cívic Pere Pruna": "Library / Civic Center",
    "Centre Cívic Sant Andreu": "Library / Civic Center",
    "Centre Cívic Sarrià": "Library / Civic Center",
    "Centre Cívic Tomasa Cuevas - Les Corts": "Library / Civic Center",
    "Centre Cívic Torre Llobeta": "Library / Civic Center",
    "Centre Cívic Vallvidrera Vázquez Montalbán": "Library / Civic Center",
    "Centre Cívic Vil·la Florida": "Library / Civic Center",
    "Centre Educatiu CETT - Escola d'Hoteleria i Turisme": "University / Education",
    "Centre Educatiu Impulsem": "University / Education",
    "Centre Educatiu Jesús Maria *Passeig Sant Gervasi": "University / Education",
    "Centre Educatiu Monlau Sagrera": "University / Education",
    "Centre Educatiu Santa Teresa - Ganduxer": "University / Education",
    "Centre Educatiu Thau": "University / Education",
    "Centre Educatiu Vedruna Gràcia Barcelona": "University / Education",
    "Centre Esportiu Municipal Can Caralleu": "Sports Facility",
    "Centre Esportiu Municipal Piscines Bernat Picornell": "Sports Facility",
    "Centre Esportiu Municipal Putxet": "Sports Facility",
    "Centre Estudis Ignasi Iglesias": "University / Education",
    "Centre Excursionista Els Blaus": "Sports Facility",
    "Centre Moral i Instructiu de Gràcia": "Library / Civic Center",
    "Centre Municipal de Cultura Popular de Sant Andreu": "Cultural Venue",
    "Centre Municipal de Vela": "Sports Facility",
    "Centre Penitenciari Obert 2  - Presó de Dones de la Trinitat": "Other",
    "Centre Superior de Disseny IED Barcelona": "University / Education",
    "Centre d'Arts Santa Mònica": "Cultural Venue",
    "Centre de Convencions Internacional de Barcelona": "Cultural Venue",
    "Centre de Cultura Contemporània de Barcelona": "Cultural Venue",
    "Centre de Cultura Popular La Violeta de Gràcia": "Cultural Venue",
    "Centre de Reunions i Convencions UAB Casa Convalescència": "Cultural Venue",
    "Centres Cívics de la Marina – Casa del Rellotge": "Library / Civic Center",
    "Cereria Subirà": "Heritage / Architecture",
    "Club Esportiu Europa": "Sports Facility",
    "Club Esportiu Mediterrani *Instal·lació Josep Vallès": "Sports Facility",
    "Club Natació Atlètic - Barceloneta": "Sports Facility",
    "Club Natació Barcelona": "Sports Facility",
    "Club Natació Catalunya": "Sports Facility",
    "Club Natació Sant Andreu": "Sports Facility",
    "Club Tennis Barcino": "Sports Facility",
    "Club Tennis La Salut": "Sports Facility",
    "Clínica Sant Jordi": "Healthcare",
    "Colmado Murria": "Heritage / Architecture",
    "Col·legi Oficial de Metges de Barcelona": "Other",
    "Col·legi d'Arquitectes de Catalunya": "Other",
    "Col·legi de Censors Jurats de Comptes de Catalunya": "Other",
    "Colònia Bausili": "Heritage / Architecture",
    "Colònia Busquets": "Heritage / Architecture",
    "Colònia Carné": "Heritage / Architecture",
    "Colònia Castells": "Heritage / Architecture",
    "Conjunt de Cases al Carrer Francisco Giner": "Heritage / Architecture",
    "Conjunt de Sant Martí de Provençals": "Heritage / Architecture",
    "Conjunt de Torretes al carrer Verdi": "Heritage / Architecture",
    "Conservatori Municipal de Música de Barcelona": "University / Education",
    "Cooperativa La Confiança Andreuenca": "Heritage / Architecture",
    "Cooperativa La Flor de Maig - sucursal núm. 7": "Heritage / Architecture",
    "Cooperativa La Guardiola Familiar": "Heritage / Architecture",
    "Cooperativa Obrera Popular Segle XX": "Heritage / Architecture",
    "CosmoCaixa Barcelona": "Museum / Gallery",
    "Cristalleries Planell": "Heritage / Architecture",
    "Círculo Ecuestre": "Other",
    "Dipòsit del Rei Martí": "Heritage / Architecture",
    "Disseny Hub Barcelona": "Museum / Gallery",
    "Drogueria Rovira (Antiga Drogueria Galvany)": "Heritage / Architecture",
    "EINA - Centre Universitari de Disseny i Art de Barcelona": "University / Education",
    "Edifici Alhambra": "Heritage / Architecture",
    "Edifici Gas Natural": "Heritage / Architecture",
    "Edifici J. Artigas": "Heritage / Architecture",
    "Edifici La Maternitat": "Heritage / Architecture",
    "Edifici La Rotonda": "Heritage / Architecture",
    "Edifici MediaTIC": "Heritage / Architecture",
    "Edifici Modernista Avinguda República Argentina 28": "Heritage / Architecture",
    "Edifici Modernista Francisco Giner 47": "Heritage / Architecture",
    "Edifici Modernista Riera de Sant Miquel 44": "Heritage / Architecture",
    "Edifici Patronat Ribas": "Heritage / Architecture",
    "Edifici Puiggròs": "Heritage / Architecture",
    "Edifici Talaia Barcelona": "Heritage / Architecture",
    "Edifici Torre Telefònica - Diagonal Zero Zero": "Heritage / Architecture",
    "Edifici d'Habitatges Gran de Gràcia 138": "Heritage / Architecture",
    "Edifici d'habitatges Gran de Gràcia 67": "Heritage / Architecture",
    "Edifici d'habitatges Gran de Gràcia 74*76": "Heritage / Architecture",
    "Edifici de La Caixa de Barcelona": "Heritage / Architecture",
    "Edifici de l'Antic Hospital de la Santa Creu": "Heritage / Architecture",
    "Edifici de la Fàbrica Moritz - Espai Gastronòmic i Cultural": "Hotel / Hospitality",
    "Educa +": "University / Education",
    "Eix Comercial del Poblenou": "Shopping Center",
    "Eix Comercial del Raval": "Shopping Center",
    "El 22@": "Other",
    "El Born i la Ribera": "Other",
    "El Born. Museu d'Història de Barcelona": "Museum / Gallery",
    "El Campus Ciutadella": "University / Education",
    "El Campus Mundet - UB": "University / Education",
    "El Campus Nord, Ciutat Universitària": "University / Education",
    "El Campus Raval - UB": "University / Education",
    "El Campus de Comunicació": "University / Education",
    "El Canal de la Infanta": "Heritage / Architecture",
    "El Clot": "Other",
    "El Congrés i els Indians": "Other",
    "El Conjunt Residencial de Les Escales Park": "Heritage / Architecture",
    "El Farró a través del carrer Saragossa": "Other",
    "El Fòrum": "Cultural Venue",
    "El Gòtic": "Other",
    "El Jardí Vertical": "Park / Garden",
    "El Paral·lel": "Other",
    "El Parc del Fòrum": "Park / Garden",
    "El Passeig de Gràcia": "Other",
    "El Passeig de les Aigües": "Park / Garden",
    "El Pla de Palau": "Other",
    "El Poble-sec": "Other",
    "El Poblenou": "Other",
    "El Polvorí i Cos de Guàrdia": "Heritage / Architecture",
    "El Portal de l'Àngel": "Shopping Center",
    "El Quadrat d'Or": "Heritage / Architecture",
    "El Raval": "Other",
    "El Rec Comtal": "Heritage / Architecture",
    "El Submarí de la Ronda": "Heritage / Architecture",
    "El Tibidabo": "Park / Garden",
    "El Túnel de la Rovira": "Heritage / Architecture",
    "El Vapor  - Fàbrica Bonaplata": "Heritage / Architecture",
    "El Vapor Nou": "Heritage / Architecture",
    "El barri Plus Ultra": "Other",
    "El barri de la Clota": "Other",
    "El barri de la Mercè": "Other",
    "El barri del Bon Pastor": "Other",
    "El camp de la Creu": "Heritage / Architecture",
    "El camí de Finestrelles, i el mirador": "Park / Garden",
    "El carrer de Bonavista": "Other",
    "El carrer de Campoamor": "Other",
    "El carrer de Canet": "Other",
    "El nucli antic d'Horta": "Heritage / Architecture",
    "El nucli de Santa Eulàlia de Vilapicina": "Heritage / Architecture",
    "El passatge d'Antoni Gassol": "Other",
    "El passatge de Mallofré": "Other",
    "El passatge de Tubella": "Other",
    "El passatge de Xile": "Other",
    "El passatge de l'Esperança": "Other",
    "El passeig de Sant Gervasi": "Other",
    "El passeig de Sant Joan": "Other",
    "El pont de Mühlberg": "Heritage / Architecture",
    "Elisava Escola Universitaria de Disseny i Enginyeria de Barcelona": "University / Education",
    "Els Edificis Trade": "Heritage / Architecture",
    "Els Jardins d'Eusebi Güell": "Park / Garden",
    "Ermita de la Mare de Déu de la Salut": "Religious Site",
    "Escola Business Engineering School - la Salle": "University / Education",
    "Escola Josep Maria Jujol": "University / Education",
    "Escola Lluís Vives": "University / Education",
    "Escola Massana Centre Municipal d'Art i Disseny": "University / Education",
    "Escola Mossèn Jacint Verdaguer": "University / Education",
    "Escola Superior d'Administració i Direcció d'Empreses - URL": "University / Education",
    "Escola Superior de Disseny i d'Art Llotja": "University / Education",
    "Escola Superior de Música de Catalunya": "University / Education",
    "Escola d'Aprenents SEAT": "Heritage / Architecture",
    "Escola la Farigola de Vallcarca": "University / Education",
    "Escullera del Port de Barcelona": "Beach / Waterfront",
    "Escultura Colles Sant Medir": "Heritage / Architecture",
    "Escultura David i Goliat Homenatge a les Brigades Internacionals": "Heritage / Architecture",
    "Escultura Fray Pedro Ponce de León": "Heritage / Architecture",
    "Escultura Josep Anselm Clavé": "Heritage / Architecture",
    "Escultura Mistos": "Heritage / Architecture",
    "Escultura Pi i Margall-La República": "Heritage / Architecture",
    "Església Antic Institut Mental": "Religious Site",
    "Església de Nostra Senyora de Pompeia": "Religious Site",
    "Església del Reial Santuari de Sant Josep de la Muntanya": "Religious Site",
    "Espai Bombers Parc de la Prevenció de Barcelona": "Other",
    "Espai Gaudí: Pis, Golfes i Terrat": "Museum / Gallery",
    "Espai Jove La Fontana": "Library / Civic Center",
    "Espai Mescladís": "Other",
    "Espai Subirachs - Poblenou": "Museum / Gallery",
    "Espai de Memòria de les Catorze Roses": "Heritage / Architecture",
    "Esplai Tr3smon": "Other",
    "Estació Barcelona-Sants de RENFE": "Transport Hub",
    "Estació d'Autobusos Barcelona Nord": "Transport Hub",
    "Estació de França": "Transport Hub",
    "Estadi Olímpic de Montjuïc Lluís Companys": "Sports Facility",
    "Fabra i Coats - Fàbrica de Creació": "Cultural Venue",
    "Facultat de Ciències de la Salut Blanquerna - URL": "University / Education",
    "Facultat de Comunicació i Relacions Internacionals Blanquerna - URL": "University / Education",
    "Facultat de Dret - UB": "University / Education",
    "Facultat de Psicologia i Ciències de l'Educació i de l'Esport Blanquerna - URL": "University / Education",
    "Far del Port - Torre del Rellotge": "Heritage / Architecture",
    "Farmàcia Clapés Viñas": "Heritage / Architecture",
    "Farmàcia Franquesa Borràs": "Heritage / Architecture",
    "Farmàcia Guinart Gómez de Arteche": "Heritage / Architecture",
    "Farmàcia Reixach-de Pablo": "Heritage / Architecture",
    "Farmàcia de Bolós Giralt": "Heritage / Architecture",
    "Federació Eix Comercial Sants-Les Corts": "Shopping Center",
    "Federació de Comerciants de Barna Centre": "Shopping Center",
    "Filmoteca de Catalunya": "Museum / Gallery",
    "Finca Sansalvador": "Heritage / Architecture",
    "Fira Barcelona": "Cultural Venue",
    "Floristeria Flora Miserachs": "Heritage / Architecture",
    "Foment Republicà de Sants. Antic Ateneu Batllori": "Heritage / Architecture",
    "Font Hércules": "Heritage / Architecture",
    "Font Màgica - Fonts de Montjuïc": "Heritage / Architecture",
    "Font Pública": "Park / Garden",
    "Forn Sarret": "Heritage / Architecture",
    "Forn de Pa Roura Vila": "Heritage / Architecture",
    "Forn de Pa de Can Tur": "Heritage / Architecture",
    "Forn de la Concepció": "Heritage / Architecture",
    "Fossar de les Moreres": "Heritage / Architecture",
    "Fundació Barcelona Media - Centre d'Innovació": "Other",
    "Fundació Joan Brossa": "Museum / Gallery",
    "Fundació Orfeó Gracienc": "Cultural Venue",
    "Fundació Privada Centre de Producció Artística i Cultural Palo Alto": "Cultural Venue",
    "Fundació Privada Foto Colectania": "Museum / Gallery",
    "Fundació Suñol": "Museum / Gallery",
    "Fundació Universitaria Agustí Pedro Pons": "University / Education",
    "Funicular Tibidabo - Cuca de Llum": "Transport Hub",
    "Funicular Vallvidrera - FGC": "Transport Hub",
    "Funicular de Montjuïc -TMB": "Transport Hub",
    "Fàbrica Artés": "Heritage / Architecture",
    "Fàbrica Sanchís": "Heritage / Architecture",
    "Fàbrica de Creació Ateneu Popular 9 Barris": "Cultural Venue",
    "Fàbrica de Creació Graner": "Cultural Venue",
    "Fàbrica de Creació Hangar": "Cultural Venue",
    "Fàbrica de Creació La Escocesa": "Cultural Venue",
    "Fàbrica de Creació Nau Ivanow": "Cultural Venue",
    "Gerència Urbanística Port Vell de l'Autoritat Portuària de Barcelona": "Other",
    "Gran Teatre del Liceu": "Cultural Venue",
    "Habitatge Classicista Providència 79": "Heritage / Architecture",
    "Herboristeria del Rei": "Heritage / Architecture",
    "Hort Urbà Masia Can Mestres": "Park / Garden",
    "Hort Urbà Masia Can Soler": "Park / Garden",
    "Hospital  Sociosanitari Mutuam Güell": "Healthcare",
    "Hospital Clínic i Provincial": "Healthcare",
    "Hospital Evangèlic": "Healthcare",
    "Hospital de la Santa Creu i Sant Pau": "Heritage / Architecture",
    "Hospital del Mar": "Healthcare",
    "Hotel Casa Fuster - HB-004219": "Hotel / Hospitality",
    "Hotel España - HB-000073": "Hotel / Hospitality",
    "Hotel Melia Barcelona Sky - HB-004358": "Hotel / Hospitality",
    "Hotel Peninsular - HB-003154": "Hotel / Hospitality",
    "Hotel W Barcelona - HB-004411 *Edifici Vela": "Hotel / Hospitality",
    "IL3 Institut de Formació Contínua - Universitat de Barcelona": "University / Education",
    "Impremta Baltasar": "Heritage / Architecture",
    "Institut Français de Barcelone": "Cultural Venue",
    "Institut Nacional d'Educació Física de Catalunya *Barcelona": "University / Education",
    "Institut Químic de Sarrià - Campus Sarrià - IQS": "University / Education",
    "Institut Vila de Gràcia": "University / Education",
    "Institut del Teatre": "University / Education",
    "Jardinets de Salvador Espriu": "Park / Garden",
    "Jardins": "Park / Garden",
    "Jardins Creu de Pedralbes": "Park / Garden",
    "Jardins Ferran Soldevila": "Park / Garden",
    "Jardins Laribal": "Park / Garden",
    "Jardins Mestre Balcells": "Park / Garden",
    "Jardins Plaça de Can Fabra": "Park / Garden",
    "Jardins d'Elvira Farreras Valentí": "Park / Garden",
    "Jardins de Can Sentmenat": "Park / Garden",
    "Jardins de Jacint Verdaguer": "Park / Garden",
    "Jardins de Joan Brossa": "Park / Garden",
    "Jardins de Joan Maragall - Palauet Albéniz": "Park / Garden",
    "Jardins de Magalí": "Park / Garden",
    "Jardins de Massana": "Park / Garden",
    "Jardins de Mossèn Costa i Llobera": "Park / Garden",
    "Jardins de Portolà": "Park / Garden",
    "Jardins de Ramon Margalef i López": "Park / Garden",
    "Jardins de Vil·la Amèlia": "Park / Garden",
    "Jardins de Vil·la Cecília": "Park / Garden",
    "Jardins de la Tamarita": "Park / Garden",
    "Jardins de les Tres Xemeneies": "Park / Garden",
    "Jardins del  Baix Guinardó": "Park / Garden",
    "Jardins del Doctor Pla i Armengol": "Park / Garden",
    "Jardins del Mirador de l'Alcalde": "Park / Garden",
    "Jardins del Palau Robert": "Park / Garden",
    "Jardins del Palau de Pedralbes": "Park / Garden",
    "Jardins del Rector Oliveras": "Park / Garden",
    "Jardins del Teatre Grec": "Park / Garden",
    "Jardins del Turó del Putxet": "Park / Garden",
    "Jardins dels Drets Humans": "Park / Garden",
    "Jardí Botànic de Barcelona": "Park / Garden",
    "Kasa de la Muntanya (KM)": "Other",
    "L'Anella Olímpica": "Sports Facility",
    "L'Antic Institut Frenopàtic": "Heritage / Architecture",
    "L'Aquàrium de Barcelona - Aspro Parks": "Museum / Gallery",
    "L'Aqüeducte Palombarum": "Heritage / Architecture",
    "L'Aqüeducte de Ciutat Meridiana": "Heritage / Architecture",
    "L'Aqüeducte del Parc Central de Nou Barris": "Heritage / Architecture",
    "L'Auditori de Barcelona": "Cultural Venue",
    "L'Espai de la Torre Melina i el seu Jardí Romàntic": "Park / Garden",
    "L'Estació de La Sagrera": "Transport Hub",
    "L'Estació dels FGC de Sarrià": "Transport Hub",
    "L'Hort del Cànem": "Park / Garden",
    "L'Hortet del Forat": "Park / Garden",
    "L'antic Putxet. Els carrers Manacor, Cadis i Putxet": "Other",
    "L'avinguda del Tibidabo": "Other",
    "L'Àrea Olímpica de la Diagonal": "Sports Facility",
    "La Barceloneta": "Other",
    "La Casa de l'Aigua": "Heritage / Architecture",
    "La Diagonal": "Other",
    "La Fàbrica del Sol": "Other",
    "La Gran Via de Carles III": "Other",
    "La Lleialtat Santsenca": "Library / Civic Center",
    "La Maquinista Terrestre i Marítima": "Heritage / Architecture",
    "La Mina Grott": "Heritage / Architecture",
    "La Model. Espai Memorial": "Heritage / Architecture",
    "La Muralla Romana": "Heritage / Architecture",
    "La Pedrera Romana": "Heritage / Architecture",
    "La Plaça Reial": "Other",
    "La Plaça Santa Madrona": "Other",
    "La Plaça de Catalunya": "Other",
    "La Plaça de Sant Jaume": "Other",
    "La Plaça de les Havaneres": "Other",
    "La Plaça del Comerç": "Other",
    "La Plaça del Mercadal": "Other",
    "La Plaça del Rom Cremat": "Other",
    "La Plaça del Setge de 1714": "Heritage / Architecture",
    "La Plaça del Sortidor": "Other",
    "La Plaça dels Indians": "Other",
    "La Porta Est de la Finca Güell": "Heritage / Architecture",
    "La Porta Sud de la Finca Güell": "Heritage / Architecture",
    "La Previsió Obrera": "Heritage / Architecture",
    "La Rambla": "Other",
    "La Rambla del Raval": "Other",
    "La Sagrera": "Other",
    "La Sardineta. Grup d'Ecoconsum de la Barceloneta": "Other",
    "La Torre Blanca": "Heritage / Architecture",
    "La Torre d'Aigües de Josep Amargós": "Heritage / Architecture",
    "La Vila Olímpica": "Other",
    "La Vil·la Hèlius (Casa Grané)": "Heritage / Architecture",
    "La Zona Universitària": "University / Education",
    "La carretera de les Aigües (sector Horta-Guinardó)": "Park / Garden",
    "La llera del riu Besòs": "Park / Garden",
    "La plaça Molina": "Other",
    "La plaça d'Espanya": "Other",
    "La plaça d'Orfila": "Other",
    "La plaça d'en Joanic": "Other",
    "La plaça de Comas": "Other",
    "La plaça de Gal·la Placídia": "Other",
    "La plaça de John Lennon": "Other",
    "La plaça de Lesseps": "Other",
    "La plaça de Nicolás Salmerón": "Other",
    "La plaça de Pedralbes": "Other",
    "La plaça de Ramon M. Roca i Sastre": "Other",
    "La plaça de Sant Gaietà": "Other",
    "La plaça de Sant Vicenç": "Other",
    "La plaça de Sarrià": "Other",
    "La plaça de la Bonanova": "Other",
    "La plaça de la Concòrdia": "Other",
    "La plaça de la Reina Maria Cristina": "Other",
    "La plaça de la Vila de Gràcia": "Other",
    "La plaça de les Glòries Catalanes": "Other",
    "La plaça del Doctor Andreu": "Other",
    "La plaça del Monestir": "Other",
    "La plaça del Poble Romaní": "Other",
    "La plaça del Raspall": "Other",
    "La rambla del Prat": "Other",
    "La vila de Gràcia": "Other",
    "Las Golondrinas - Sirenas SA": "Transport Hub",
    "Les Carasses": "Heritage / Architecture",
    "Les Corts": "Other",
    "Masia Ca l'Armera": "Heritage / Architecture",
    "Masia Can Fargas": "Heritage / Architecture",
    "Masia Can Rosés": "Heritage / Architecture",
    "Masia Can Valent": "Heritage / Architecture",
    "Masia Torre Rodona - Can Vinyals de la Torre": "Heritage / Architecture",
    "Masia de Can Baró": "Heritage / Architecture",
    "Masia la Petita Maria": "Heritage / Architecture",
    "Masoveria de la Virreina": "Heritage / Architecture",
    "Memorial de les Dones Represaliades a la Presó de Dones de les Corts": "Heritage / Architecture",
    "Memorial en Record de les Víctimes de Trànsit": "Heritage / Architecture",
    "Menjadors populars del carrer Gran Sant Andreu (Guerra Civil)": "Heritage / Architecture",
    "Mercat Abaceria Central": "Market",
    "Mercat Barceloneta": "Market",
    "Mercat Boqueria - Sant Josep": "Market",
    "Mercat Clot": "Market",
    "Mercat Concepció": "Market",
    "Mercat Encants Barcelona - Fira de Bellcaire": "Market",
    "Mercat Galvany": "Market",
    "Mercat Guineueta": "Market",
    "Mercat Horta": "Market",
    "Mercat Hostafrancs": "Market",
    "Mercat Les Corts": "Market",
    "Mercat Llibertat": "Market",
    "Mercat Ninot": "Market",
    "Mercat Núria": "Market",
    "Mercat Poblenou - Unió": "Market",
    "Mercat Sant Andreu": "Market",
    "Mercat Sant Antoni": "Market",
    "Mercat Santa Caterina": "Market",
    "Mercat Sants": "Market",
    "Mercat Sarrià": "Market",
    "Mercat de les Flors Centre de les Arts de Moviment": "Cultural Venue",
    "Metro Fontana": "Transport Hub",
    "Mirador Joan Sales i Vallès": "Park / Garden",
    "Moll de la Fusta": "Beach / Waterfront",
    "Moll de la Fusta *Escenari Besòs": "Cultural Venue",
    "Moll de la Fusta *Escenari Llobregat": "Cultural Venue",
    "Molí de Sant Andreu - Rec Comtal": "Heritage / Architecture",
    "Monestir de Sant Pau del Camp": "Religious Site",
    "Monestir de Santa Maria de Valldonzella": "Religious Site",
    "Monument Arc de Triomf de Barcelona": "Heritage / Architecture",
    "Monument a Cristòfol Colom": "Heritage / Architecture",
    "Monument a Josep Tarradellas": "Heritage / Architecture",
    "Mooby Bosque Multicines": "Cultural Venue",
    "Mural de la Memòria de Baró de Viver": "Heritage / Architecture",
    "Museu": "Museum / Gallery",
    "Museu Barça Immersive Tour": "Museum / Gallery",
    "Museu Egipci de Barcelona": "Museum / Gallery",
    "Museu Etnològic i de Cultures del Món *Parc Montjuïc": "Museum / Gallery",
    "Museu Frederic Marès": "Museum / Gallery",
    "Museu Marítim de Barcelona": "Museum / Gallery",
    "Museu Nacional d'Art de Catalunya": "Museum / Gallery",
    "Museu Olímpic i de l'Esport Joan Antoni Samaranch de Barcelona": "Museum / Gallery",
    "Museu Palmero Arte": "Museum / Gallery",
    "Museu Picasso": "Museum / Gallery",
    "Museu Reial Monestir de Santa Maria de Pedralbes": "Museum / Gallery",
    "Museu Tàpies": "Museum / Gallery",
    "Museu d'Arqueologia de Catalunya": "Museum / Gallery",
    "Museu d'Art Contemporani de Barcelona": "Museum / Gallery",
    "Museu d'Autòmats del Tibidabo": "Museum / Gallery",
    "Museu de Carruatges del Foment": "Museum / Gallery",
    "Museu de Cera de Barcelona": "Museum / Gallery",
    "Museu de Ciències Naturals de Barcelona": "Museum / Gallery",
    "Museu de Pintura Contemporània Can Framis": "Museum / Gallery",
    "Museu de la Xocolata": "Museum / Gallery",
    "Oasi MAC": "Museum / Gallery",
    "Obelisc del Cinc d'Oros": "Heritage / Architecture",
    "Observatori Fabra": "Heritage / Architecture",
    "OikoCrèdit Catalunya": "Other",
    "Oliva Artés. Museu d'Història de Barcelona": "Museum / Gallery",
    "Oratori de Sant Felip Neri *Gràcia": "Religious Site",
    "Palau Güell": "Heritage / Architecture",
    "Palau Macaya": "Heritage / Architecture",
    "Palau Montaner": "Heritage / Architecture",
    "Palau Reial de Pedralbes": "Heritage / Architecture",
    "Palau Robert": "Heritage / Architecture",
    "Palau Sant Jordi": "Sports Facility",
    "Palau de Congressos *Pavelló 5": "Cultural Venue",
    "Palau de Congressos de Catalunya": "Cultural Venue",
    "Palau de Mar": "Heritage / Architecture",
    "Palau de la Música Catalana": "Cultural Venue",
    "Palau de la Premsa": "Heritage / Architecture",
    "Palau de la Virreina": "Cultural Venue",
    "Palau del Baró de Quadras": "Heritage / Architecture",
    "Parc Carmel": "Park / Garden",
    "Parc Central de Nou Barris": "Park / Garden",
    "Parc Científic de Barcelona": "University / Education",
    "Parc Esportiu de Can Dragó": "Sports Facility",
    "Parc Metropolità Collserola": "Park / Garden",
    "Parc Sanitari Pere Virgili": "Healthcare",
    "Parc Torrent Maduixer": "Park / Garden",
    "Parc d'Atraccions del Tibidabo": "Museum / Gallery",
    "Parc de Can Rigal": "Park / Garden",
    "Parc de Can Sabaté": "Park / Garden",
    "Parc de Cervantes": "Park / Garden",
    "Parc de Diagonal Mar": "Park / Garden",
    "Parc de Joan Miró": "Park / Garden",
    "Parc de Monterols": "Park / Garden",
    "Parc de Montjuïc": "Park / Garden",
    "Parc de Recerca Biomèdica de Barcelona": "University / Education",
    "Parc de Sant Martí": "Park / Garden",
    "Parc de l'Espanya Industrial": "Park / Garden",
    "Parc de la Barceloneta": "Park / Garden",
    "Parc de la Ciutadella": "Park / Garden",
    "Parc de la Creueta del Coll": "Park / Garden",
    "Parc de la Font Florida": "Park / Garden",
    "Parc de la Font del Racó": "Park / Garden",
    "Parc de la Guineueta": "Park / Garden",
    "Parc de la Maquinista per les treballadores i els treballadors de la Maquinista": "Park / Garden",
    "Parc de la Pegaso": "Park / Garden",
    "Parc de la Primavera": "Park / Garden",
    "Parc de la Trinitat": "Park / Garden",
    "Parc de les Aigües": "Park / Garden",
    "Parc de les Cascades": "Park / Garden",
    "Parc de les Rieres d'Horta": "Park / Garden",
    "Parc del Castell de l'Oreneta": "Park / Garden",
    "Parc del Centre del Poblenou": "Park / Garden",
    "Parc del Clot": "Park / Garden",
    "Parc del Guinardó": "Park / Garden",
    "Parc del Laberint d'Horta": "Park / Garden",
    "Parc del Mirador del Poble-sec": "Park / Garden",
    "Parc del Poblenou": "Park / Garden",
    "Parc del Turó de la Peira": "Park / Garden",
    "Park Güell": "Park / Garden",
    "Parròquia de Maria Auxiliadora": "Religious Site",
    "Parròquia de Maria Reina": "Religious Site",
    "Parròquia de Sant Genís dels Agudells": "Religious Site",
    "Parròquia de Sant Gregori Taumaturg": "Religious Site",
    "Parròquia de Sant Joan de Gràcia": "Religious Site",
    "Parròquia de Sant Josep Manyanet": "Religious Site",
    "Parròquia de Sant Medir": "Religious Site",
    "Parròquia de Sant Pacià": "Religious Site",
    "Parròquia de Sant Pere de les Puel·les": "Religious Site",
    "Parròquia de Sant Ramon Nonat": "Religious Site",
    "Parròquia de Sant Vicenç de Sarrià": "Religious Site",
    "Parròquia de Santa Madrona": "Religious Site",
    "Parròquia de Santa Maria de Gràcia": "Religious Site",
    "Parròquia de Santa Maria del Mar - Basílica": "Religious Site",
    "Parròquia de Santa Maria del Pi - Basílica": "Religious Site",
    "Parròquia de Santa Maria del Remei": "Religious Site",
    "Parròquia de Santa Teresa de l'Infant Jesús": "Religious Site",
    "Parròquia de l'Immaculat Cor de Maria": "Religious Site",
    "Parròquia de la Mare de Déu de Lourdes": "Religious Site",
    "Parròquia de la Mare de Déu de la Mercè i Sant Miquel Arcàngel - Basílica": "Religious Site",
    "Parròquia de la Mare de Déu del Coll": "Religious Site",
    "Parròquia de la Santíssima Trinitat": "Religious Site",
    "Parròquia de la Verge de Gràcia i Sant Josep": "Religious Site",
    "Parròquia rural de Santa Maria de Vallvidrera": "Religious Site",
    "Passatge de Sant Felip": "Other",
    "Passeig Lluis Companys - Arc de Triomf": "Other",
    "Pastisseria Escribà *La Rambla": "Heritage / Architecture",
    "Pati Geològic": "Museum / Gallery",
    "Pavellons d'Entrada de l'Antiga Finca Güell": "Heritage / Architecture",
    "Pavelló Mies van der Rohe": "Heritage / Architecture",
    "Pavelló de Ràdio Barcelona al Parc d'Atraccions del Tibidabo": "Heritage / Architecture",
    "Pavelló de la República": "Heritage / Architecture",
    "Pilar d'Aigua de Sant Andreu": "Heritage / Architecture",
    "Pilar d'Aigua de la Sagrera": "Heritage / Architecture",
    "Pis - Museu Habitatge 1/11": "Museum / Gallery",
    "Pla de Montbau": "Other",
    "Pla de l'Os - La Rambla": "Heritage / Architecture",
    "Pla de la Seu": "Other",
    "Places de Joaquim Folguera i Frederic Soler": "Other",
    "Platja de Llevant": "Beach / Waterfront",
    "Platja de Sant Sebastià": "Beach / Waterfront",
    "Platja de l'Espigó del Gas": "Beach / Waterfront",
    "Platja de la Barceloneta": "Beach / Waterfront",
    "Platja de la Mar Bella": "Beach / Waterfront",
    "Platja de la Nova Icària": "Beach / Waterfront",
    "Platja de la Nova Mar Bella": "Beach / Waterfront",
    "Platja del Bogatell": "Beach / Waterfront",
    "Plaça Eivissa": "Other",
    "Plaça Major de Nou Barris": "Other",
    "Plaça Masadas": "Other",
    "Plaça de Rovira i Trias": "Other",
    "Plaça de la Mercè": "Other",
    "Plaça de la Revolució": "Other",
    "Plaça de la Virreina": "Other",
    "Plaça de les Dones del 36": "Other",
    "Plaça del Nen de la Rutlla": "Other",
    "Plaça del Nord": "Other",
    "Plaça del Rei": "Heritage / Architecture",
    "Plaça del Sol": "Other",
    "Plaça dels Àngels": "Other",
    "Poble Espanyol de Barcelona": "Museum / Gallery",
    "Pont de Calatrava (Bac de Roda - Felip II)": "Heritage / Architecture",
    "Port Olímpic de Barcelona": "Beach / Waterfront",
    "Portal Casa Miralles": "Heritage / Architecture",
    "Premsa de Vi de Can Xandri": "Heritage / Architecture",
    "Pèrgola Fotovoltaica al Parc del Fòrum": "Other",
    "Quarter Bruc": "Heritage / Architecture",
    "Rambla de Fabra i Puig": "Other",
    "Refugi 307.  Museu d'Història de Barcelona": "Museum / Gallery",
    "Refugi Antiaeri 977 (Matanzas / Pinar del Río)": "Heritage / Architecture",
    "Refugi Antiaeri de Can Peguera": "Heritage / Architecture",
    "Refugi Antiaeri de La Lira": "Heritage / Architecture",
    "Refugi Antiaeri de la Plaça del Diamant": "Heritage / Architecture",
    "Refugi Antiaeri de la Sagrera": "Heritage / Architecture",
    "Refugi antiaeri 292 carrer Piquer del Poble-sec": "Heritage / Architecture",
    "Reial Acadèmia de Ciències i Arts de Barcelona": "Other",
    "Reial Acadèmia de Medicina de Catalunya": "Other",
    "Reial Club Nàutic de Barcelona": "Sports Facility",
    "Reial Club de Polo de Barcelona": "Sports Facility",
    "Reial Club de Tennis Barcelona - 1899": "Sports Facility",
    "Reials Drassanes de Barcelona": "Heritage / Architecture",
    "Religioses de la Mare de Déu de la Mercè": "Religious Site",
    "Residència Assistencial per a Gent Gran Refugi d'Obreres": "Healthcare",
    "Residència Assistida per a Gent Gran Llars Mundet": "Healthcare",
    "Residència Militar d'Estudiants Mateo Calabro": "Other",
    "Residència Salesiana Martí Codolar": "Other",
    "Restaurant Bonanova": "Hotel / Hospitality",
    "Restaurant Can Cortada": "Hotel / Hospitality",
    "Restaurant Can Travi Nou": "Hotel / Hospitality",
    "Restaurant Casa Tejada": "Hotel / Hospitality",
    "Restaurant Casa Trampa": "Hotel / Hospitality",
    "Restaurant Dos Torres": "Hotel / Hospitality",
    "Restaurant El Asador de Aranda *Av Tibidabo": "Hotel / Hospitality",
    "Roca Barcelona Gallery": "Museum / Gallery",
    "Ronda de Sant Antoni": "Other",
    "Sala El Molino": "Cultural Venue",
    "Sala Lliure de Gràcia": "Cultural Venue",
    "Sant Andreu": "Other",
    "Sant Andreu Teatre": "Cultural Venue",
    "Sant Antoni": "Other",
    "Sant Joan de Dalt": "Other",
    "Sant Pau Recinte Modernista": "Heritage / Architecture",
    "Sant Pere i Santa Caterina": "Other",
    "Santa Creu d'Olorda": "Park / Garden",
    "Santa Església Catedral Basílica de Barcelona": "Religious Site",
    "Sants i Hostafrancs": "Other",
    "Santuari de Santa Eulàlia de Vilapicina": "Religious Site",
    "Sarrià": "Other",
    "Servei d'Esports de la Universitat de Barcelona": "Sports Facility",
    "Seu de l'Antiga Hidroelèctrica de Catalunya": "Heritage / Architecture",
    "Seu de la Secció 10 de les Patrulles de Control (Guerra Civil)": "Heritage / Architecture",
    "Seu del Districte de Nou Barris": "Other",
    "Seu del Districte de Sant Andreu": "Other",
    "Seu del Districte de Sants-Montjuïc": "Other",
    "Seu del Districte de Sarrià-Sant Gervasi": "Other",
    "Spotify Camp Nou": "Sports Facility",
    "TAMAIA Viure Sense Violencia, S.C.C.L.": "Other",
    "Teatre Coliseum": "Cultural Venue",
    "Teatre Grec": "Cultural Venue",
    "Teatre Lliure": "Cultural Venue",
    "Teatre Nacional de Catalunya": "Cultural Venue",
    "Teatro de los Sentidos": "Cultural Venue",
    "Telefèric de Barcelona": "Transport Hub",
    "Telefèric de Montjuïc": "Transport Hub",
    "Temple Expiatori de la Sagrada Família - Basílica": "Religious Site",
    "Tinta Invisible Edicions": "Other",
    "Torre Bellesguard  Gaudí - Casa Figueres": "Heritage / Architecture",
    "Torre Castanyer": "Heritage / Architecture",
    "Torre Glòries": "Heritage / Architecture",
    "Torre Jussana - Centre de Serveis a les Associacions": "Library / Civic Center",
    "Torre Montjuïc Calatrava": "Heritage / Architecture",
    "Torre d'Aigües de Carrasco i Formiguera": "Heritage / Architecture",
    "Torre d'Ignacio Portabella": "Heritage / Architecture",
    "Torre de Collserola": "Heritage / Architecture",
    "Torre de Sant Jordi": "Heritage / Architecture",
    "Torre de Santa Caterina": "Heritage / Architecture",
    "Torre de l'Aigua": "Heritage / Architecture",
    "Torre de la Catalana de Gas": "Heritage / Architecture",
    "Torre de les Aigües del Besòs": "Heritage / Architecture",
    "Torre del Doctor Andreu": "Heritage / Architecture",
    "Torre del Fang": "Heritage / Architecture",
    "Torre del Rellotge": "Heritage / Architecture",
    "Tramvia Blau Tibidabo-TMB": "Transport Hub",
    "Turó Park - Parc del Poeta Eduard Marquina": "Park / Garden",
    "Universitat Internacional de Catalunya": "University / Education",
    "Universitat Nacional d'Educació a Distància *Barcelona": "University / Education",
    "Universitat Oberta de Catalunya": "University / Education",
    "Universitat Politècnica de Catalunya": "University / Education",
    "Universitat de Barcelona": "University / Education",
    "Unió de Botiguers del Cor d'Horta": "Shopping Center",
    "Unió de Cooperatives per a la Fabricació de Pastes per a Sopa": "Other",
    "Vall d'Hebron Barcelona Hospital Campus": "Healthcare",
    "Velodrom Municipal d'Horta Miquel Poblet": "Sports Facility",
    "Viaducte de Bellesguard": "Heritage / Architecture",
    "Viaducte de Vallcarca": "Heritage / Architecture",
    "Villa Conchita o Casa dels Metges": "Heritage / Architecture",
    "Villa Esperanza": "Heritage / Architecture",
    "Vil·la Joana. Museu d'Història de Barcelona": "Museum / Gallery",
    "World Trade Center": "Other",
    "Xemeneia de Can Galta Cremat": "Heritage / Architecture",
    'Xemeneia de l\'antiga Fábrica "La Porcelana"': "Heritage / Architecture",
    "Zona de Banys": "Beach / Waterfront",
    "Zoo de Barcelona": "Museum / Gallery",
    "Àntic Edifici de Catalana de Gas i Electricitat, SA": "Heritage / Architecture",
    "Àntiga Fàbrica de Làmpades Z": "Heritage / Architecture",
}


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    log.info("Reading %s", RAW_FILE.name)
    df = pd.read_csv(RAW_FILE, encoding="utf-16", usecols=KEEP_COLS)

    # Bounding box for Barcelona municipality
    BCN_LAT = (41.32, 41.50)
    BCN_LON = (2.05, 2.23)
    before = len(df)
    df = df[
        df["geo_epgs_4326_lat"].between(*BCN_LAT)
        & df["geo_epgs_4326_lon"].between(*BCN_LON)
    ].copy()
    log.info("Dropped %d POIs outside Barcelona bbox (%d remaining)", before - len(df), len(df))

    log.info("Applying category labels to %d POIs…", len(df))
    df["category"] = df["name"].map(LABELS)

    unlabeled = df["category"].isna().sum()
    if unlabeled:
        log.warning("%d POIs could not be matched to a label:", unlabeled)
        for name in df.loc[df["category"].isna(), "name"]:
            log.warning("  — %s", name)
        df["category"] = df["category"].fillna("Other")

    df.to_parquet(OUT_FILE, index=False)
    log.info("Saved → %s", OUT_FILE)

    print("\n=== Summary ===")
    print(f"Total POIs:  {len(df)}")
    print(f"Labeled:     {(df['category'] != 'Other').sum()} (non-Other)")
    print()
    counts = df["category"].value_counts()
    for cat, n in counts.items():
        print(f"  {n:>4}  {cat}")
    print(f"\nOutput: {OUT_FILE}")


if __name__ == "__main__":
    main()
